regno= int(input("enter your regno:"))
name = input("Enter student name: ")
age = int(input("Enter age: "))
department = input("Enter department: ")
college_name = input("Enter college name: ")
cgpa = float(input("Enter cgpa: "))

print("\n--- Student Information ---")
print("Regno:", regno)
print("Name:", name)
print("Age:", age)
print("Dept:", department)
print("College:", college_name)
print("CPGA:", cgpa)
